### ISSUE TITLE
The f1 addresses extracted by getAddressAndPubKey in ledger-filecoin-js are not the same as the f1 addresses in Ledger Live's Filecoin. Interestingly, only the first and second addresses are identical; all the other addresses are different.

### ISSUE THREAD

**Issue by 597800451** [Zondax/ledger-filecoin-js#66]
This is the code I use to extract addresses in JavaScript

`let res = await app.getAddressAndPubKey(“m/44'/461'/0'/0/0”)`
`let res = await app.getAddressAndPubKey(“m/44'/461'/0'/0/1”)`
`let res = await app.getAddressAndPubKey(“m/44'/461'/0'/0/2”)`
`let res = await app.getAddressAndPubKey(“m/44'/461'/0'/0/3”)`
`let res = await app.getAddressAndPubKey(“m/44'/461'/0'/0/4”)`

![image](https://github.com/Zondax/ledger-filecoin-js/assets/5043738/fa40578d-ea3e-4e56-a4c1-641934180060)

![image](https://github.com/Zondax/ledger-filecoin-js/assets/5043738/c91f5acc-7a98-452c-9ff2-4c1f29444a9e)

![image](https://github.com/Zondax/ledger-filecoin-js/assets/5043738/44b71417-a742-42b2-9c93-e6882648f696)

![image](https://github.com/Zondax/ledger-filecoin-js/assets/5043738/bd2ad641-6f9b-4af1-99cc-5af1ebcfc859)

![image](https://github.com/Zondax/ledger-filecoin-js/assets/5043738/fad47c6c-2011-4622-b725-ccb428c3ed10)

The third address is different, which is strange because the first and second addresses are the same.

**Comment by jleni** [comment]
Could you confirm what you have in the derivation paths of those accounts in Ledger Live?

![image](https://github.com/Zondax/ledger-filecoin-js/assets/13698520/ebb694e1-385b-4c00-8761-abf5eafbe561)

Ledger Live sometimes iterates accounts in a different way,.

**Comment by 597800451** [comment]
![image](https://github.com/Zondax/ledger-filecoin-js/assets/5043738/a768d83f-3f57-4d20-8ca7-e5e31377faab)
Haha, found the issue, it's indeed different, thank you. Why can't it be unified?
