### ISSUE TITLE
Does it support plain string signing, like Metamask's personal_sign?

### ISSUE THREAD

**Issue by 597800451** [Zondax/ledger-filecoin-js#67]
Used for identity verification in dapps. Can it sign a string message like Metamask does? Then the backend performs signature verification.

eth app is supported
![fa80b6c0e0b10b125d0f5a4e99be064](https://github.com/Zondax/ledger-filecoin-js/assets/5043738/5bcfe9ed-d87a-4382-bb01-91c9ff4e2449)
![9730f78a082a151dd1053a68ad3183e](https://github.com/Zondax/ledger-filecoin-js/assets/5043738/282d6afa-cbbe-4cb3-afe1-68a54532c056)
![e2a6c6fff238f14abbfe68fd4341e85](https://github.com/Zondax/ledger-filecoin-js/assets/5043738/be4d8be6-aea6-4f94-a48c-a0d672c75902)

Is the Filecoin app supported?

**Comment by 597800451** [comment]
@jleni

**Comment by ftheirs** [comment]
Hi @597800451, could you open the issues related to the app in https://github.com/Zondax/ledger-filecoin/ 🙏 
Have you checked this: `signRawBytes` this should allow you to sign a message but remember to add the prefix (`Filecoin Sign Bytes:\n`)
Is this your issue or you are trying to sign an ETH message?

**Comment by 597800451** [comment]
> Hi @597800451, could you open the issues related to the app in https://github.com/Zondax/ledger-filecoin/ 🙏 Have you checked this: `signRawBytes` this should allow you to sign a message but remember to add the prefix (`Filecoin Sign Bytes:\n`) Is this your issue or you are trying to sign an ETH message?

When I attempt to use signRawBytes, the Ledger returns `{return_code: 27012, error_message: 'Data is invalid : '}`, and my Ledger gets stuck displaying `RawBytes: Chunk:0` 
I suspect there may be an issue with the parameters I'm passing. Could you provide an example and teach me how to pass the parameters correctly? Here is my current code:

```
let message = 'hello'
let path = this._getPath(this.account)
try {
    
    let _msg = Buffer.from('Filecoin Sign Bytes:\n' + message, 'hex')
    
    let res = await filecoinApp.signRawBytes(path, _msg)
    console.log(res)
} catch (e) {
    console.log(e)
    throw e
}
```
![73efbc8f1c53b49145860cb8c56771f](https://github.com/Zondax/ledger-filecoin-js/assets/5043738/ab1febe8-65f1-4d46-a622-558d0f21770b)
